// Generated by gencpp from file upros_message/ArmPosition.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_ARMPOSITION_H
#define UPROS_MESSAGE_MESSAGE_ARMPOSITION_H

#include <ros/service_traits.h>


#include <upros_message/ArmPositionRequest.h>
#include <upros_message/ArmPositionResponse.h>


namespace upros_message
{

struct ArmPosition
{

typedef ArmPositionRequest Request;
typedef ArmPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmPosition
} // namespace upros_message


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upros_message::ArmPosition > {
  static const char* value()
  {
    return "0666436500748dda2dc9db59684c43ec";
  }

  static const char* value(const ::upros_message::ArmPosition&) { return value(); }
};

template<>
struct DataType< ::upros_message::ArmPosition > {
  static const char* value()
  {
    return "upros_message/ArmPosition";
  }

  static const char* value(const ::upros_message::ArmPosition&) { return value(); }
};


// service_traits::MD5Sum< ::upros_message::ArmPositionRequest> should match
// service_traits::MD5Sum< ::upros_message::ArmPosition >
template<>
struct MD5Sum< ::upros_message::ArmPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upros_message::ArmPosition >::value();
  }
  static const char* value(const ::upros_message::ArmPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upros_message::ArmPositionRequest> should match
// service_traits::DataType< ::upros_message::ArmPosition >
template<>
struct DataType< ::upros_message::ArmPositionRequest>
{
  static const char* value()
  {
    return DataType< ::upros_message::ArmPosition >::value();
  }
  static const char* value(const ::upros_message::ArmPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upros_message::ArmPositionResponse> should match
// service_traits::MD5Sum< ::upros_message::ArmPosition >
template<>
struct MD5Sum< ::upros_message::ArmPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upros_message::ArmPosition >::value();
  }
  static const char* value(const ::upros_message::ArmPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upros_message::ArmPositionResponse> should match
// service_traits::DataType< ::upros_message::ArmPosition >
template<>
struct DataType< ::upros_message::ArmPositionResponse>
{
  static const char* value()
  {
    return DataType< ::upros_message::ArmPosition >::value();
  }
  static const char* value(const ::upros_message::ArmPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_ARMPOSITION_H
