// Generated by gencpp from file upros_message/ArmPositionResponse.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_ARMPOSITIONRESPONSE_H
#define UPROS_MESSAGE_MESSAGE_ARMPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct ArmPositionResponse_
{
  typedef ArmPositionResponse_<ContainerAllocator> Type;

  ArmPositionResponse_()
    : status(0)  {
    }
  ArmPositionResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::upros_message::ArmPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::ArmPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmPositionResponse_

typedef ::upros_message::ArmPositionResponse_<std::allocator<void> > ArmPositionResponse;

typedef boost::shared_ptr< ::upros_message::ArmPositionResponse > ArmPositionResponsePtr;
typedef boost::shared_ptr< ::upros_message::ArmPositionResponse const> ArmPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::ArmPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::ArmPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::ArmPositionResponse_<ContainerAllocator1> & lhs, const ::upros_message::ArmPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::ArmPositionResponse_<ContainerAllocator1> & lhs, const ::upros_message::ArmPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::ArmPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::ArmPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::ArmPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::upros_message::ArmPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/ArmPositionResponse";
  }

  static const char* value(const ::upros_message::ArmPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
;
  }

  static const char* value(const ::upros_message::ArmPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::ArmPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::ArmPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_ARMPOSITIONRESPONSE_H
