// Generated by gencpp from file upros_message/CoreMoveGoal.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_COREMOVEGOAL_H
#define UPROS_MESSAGE_MESSAGE_COREMOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace upros_message
{
template <class ContainerAllocator>
struct CoreMoveGoal_
{
  typedef CoreMoveGoal_<ContainerAllocator> Type;

  CoreMoveGoal_()
    : cmd(0)
    , target_pose()  {
    }
  CoreMoveGoal_(const ContainerAllocator& _alloc)
    : cmd(0)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TURN_AROUND)
  #undef TURN_AROUND
#endif
#if defined(_WIN32) && defined(GO_STRIGHT)
  #undef GO_STRIGHT
#endif

  enum {
    TURN_AROUND = 0,
    GO_STRIGHT = 1,
  };


  typedef boost::shared_ptr< ::upros_message::CoreMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::CoreMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CoreMoveGoal_

typedef ::upros_message::CoreMoveGoal_<std::allocator<void> > CoreMoveGoal;

typedef boost::shared_ptr< ::upros_message::CoreMoveGoal > CoreMoveGoalPtr;
typedef boost::shared_ptr< ::upros_message::CoreMoveGoal const> CoreMoveGoalConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::CoreMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::CoreMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::CoreMoveGoal_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::CoreMoveGoal_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1e16158e8d38eb2844c9923667d0a0c";
  }

  static const char* value(const ::upros_message::CoreMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1e16158e8d38eb2ULL;
  static const uint64_t static_value2 = 0x844c9923667d0a0cULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/CoreMoveGoal";
  }

  static const char* value(const ::upros_message::CoreMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 TURN_AROUND=0\n"
"int8 GO_STRIGHT=1\n"
"int8 cmd\n"
"geometry_msgs/PoseStamped target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::upros_message::CoreMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoreMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::CoreMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::CoreMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_COREMOVEGOAL_H
