// Generated by gencpp from file upros_message/CoreMoveResult.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_COREMOVERESULT_H
#define UPROS_MESSAGE_MESSAGE_COREMOVERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <actionlib_msgs/GoalStatus.h>

namespace upros_message
{
template <class ContainerAllocator>
struct CoreMoveResult_
{
  typedef CoreMoveResult_<ContainerAllocator> Type;

  CoreMoveResult_()
    : final_result(0)
    , status()  {
    }
  CoreMoveResult_(const ContainerAllocator& _alloc)
    : final_result(0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _final_result_type;
  _final_result_type final_result;

   typedef  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::upros_message::CoreMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::CoreMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct CoreMoveResult_

typedef ::upros_message::CoreMoveResult_<std::allocator<void> > CoreMoveResult;

typedef boost::shared_ptr< ::upros_message::CoreMoveResult > CoreMoveResultPtr;
typedef boost::shared_ptr< ::upros_message::CoreMoveResult const> CoreMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::CoreMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::CoreMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::CoreMoveResult_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_result == rhs.final_result &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::CoreMoveResult_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::CoreMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72c60a262b95b5cb73e7d1792112f25d";
  }

  static const char* value(const ::upros_message::CoreMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72c60a262b95b5cbULL;
  static const uint64_t static_value2 = 0x73e7d1792112f25dULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::CoreMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/CoreMoveResult";
  }

  static const char* value(const ::upros_message::CoreMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::CoreMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 final_result\n"
"actionlib_msgs/GoalStatus status\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
;
  }

  static const char* value(const ::upros_message::CoreMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::CoreMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_result);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoreMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::CoreMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::CoreMoveResult_<ContainerAllocator>& v)
  {
    s << indent << "final_result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_result);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_COREMOVERESULT_H
