// Generated by gencpp from file upros_message/CoreMoveFeedback.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_COREMOVEFEEDBACK_H
#define UPROS_MESSAGE_MESSAGE_COREMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace upros_message
{
template <class ContainerAllocator>
struct CoreMoveFeedback_
{
  typedef CoreMoveFeedback_<ContainerAllocator> Type;

  CoreMoveFeedback_()
    : runing(0)
    , current_position()  {
    }
  CoreMoveFeedback_(const ContainerAllocator& _alloc)
    : runing(0)
    , current_position(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _runing_type;
  _runing_type runing;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;





  typedef boost::shared_ptr< ::upros_message::CoreMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::CoreMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CoreMoveFeedback_

typedef ::upros_message::CoreMoveFeedback_<std::allocator<void> > CoreMoveFeedback;

typedef boost::shared_ptr< ::upros_message::CoreMoveFeedback > CoreMoveFeedbackPtr;
typedef boost::shared_ptr< ::upros_message::CoreMoveFeedback const> CoreMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::CoreMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::CoreMoveFeedback_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.runing == rhs.runing &&
    lhs.current_position == rhs.current_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::CoreMoveFeedback_<ContainerAllocator1> & lhs, const ::upros_message::CoreMoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::CoreMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::CoreMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::CoreMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16ad7b9381f50b83dafc17a9791c2ffb";
  }

  static const char* value(const ::upros_message::CoreMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16ad7b9381f50b83ULL;
  static const uint64_t static_value2 = 0xdafc17a9791c2ffbULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/CoreMoveFeedback";
  }

  static const char* value(const ::upros_message::CoreMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 runing\n"
"geometry_msgs/PoseStamped current_position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::upros_message::CoreMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.runing);
      stream.next(m.current_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoreMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::CoreMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::CoreMoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "runing: ";
    Printer<int8_t>::stream(s, indent + "  ", v.runing);
    s << indent << "current_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_COREMOVEFEEDBACK_H
