// Generated by gencpp from file upros_message/MultipleServo.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MULTIPLESERVO_H
#define UPROS_MESSAGE_MESSAGE_MULTIPLESERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <upros_message/SingleServo.h>

namespace upros_message
{
template <class ContainerAllocator>
struct MultipleServo_
{
  typedef MultipleServo_<ContainerAllocator> Type;

  MultipleServo_()
    : servo_gather()  {
    }
  MultipleServo_(const ContainerAllocator& _alloc)
    : servo_gather(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::upros_message::SingleServo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::upros_message::SingleServo_<ContainerAllocator> >> _servo_gather_type;
  _servo_gather_type servo_gather;





  typedef boost::shared_ptr< ::upros_message::MultipleServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::MultipleServo_<ContainerAllocator> const> ConstPtr;

}; // struct MultipleServo_

typedef ::upros_message::MultipleServo_<std::allocator<void> > MultipleServo;

typedef boost::shared_ptr< ::upros_message::MultipleServo > MultipleServoPtr;
typedef boost::shared_ptr< ::upros_message::MultipleServo const> MultipleServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::MultipleServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::MultipleServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::MultipleServo_<ContainerAllocator1> & lhs, const ::upros_message::MultipleServo_<ContainerAllocator2> & rhs)
{
  return lhs.servo_gather == rhs.servo_gather;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::MultipleServo_<ContainerAllocator1> & lhs, const ::upros_message::MultipleServo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::MultipleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::MultipleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MultipleServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MultipleServo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MultipleServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MultipleServo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::MultipleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0bba86e4a57a4c36bff2c5c90926b54";
  }

  static const char* value(const ::upros_message::MultipleServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0bba86e4a57a4c3ULL;
  static const uint64_t static_value2 = 0x6bff2c5c90926b54ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::MultipleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/MultipleServo";
  }

  static const char* value(const ::upros_message::MultipleServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::MultipleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SingleServo[] servo_gather\n"
"================================================================================\n"
"MSG: upros_message/SingleServo\n"
"uint8 ID\n"
"int16 Target_position_Angle\n"
"uint16 Rotation_Speed\n"
;
  }

  static const char* value(const ::upros_message::MultipleServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::MultipleServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_gather);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultipleServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::MultipleServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::MultipleServo_<ContainerAllocator>& v)
  {
    s << indent << "servo_gather[]" << std::endl;
    for (size_t i = 0; i < v.servo_gather.size(); ++i)
    {
      s << indent << "  servo_gather[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::upros_message::SingleServo_<ContainerAllocator> >::stream(s, indent + "    ", v.servo_gather[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MULTIPLESERVO_H
