// Generated by gencpp from file upros_message/MyActionFeedback.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MYACTIONFEEDBACK_H
#define UPROS_MESSAGE_MESSAGE_MYACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct MyActionFeedback_
{
  typedef MyActionFeedback_<ContainerAllocator> Type;

  MyActionFeedback_()
    : progress(0.0)  {
    }
  MyActionFeedback_(const ContainerAllocator& _alloc)
    : progress(0.0)  {
  (void)_alloc;
    }



   typedef float _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::upros_message::MyActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::MyActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MyActionFeedback_

typedef ::upros_message::MyActionFeedback_<std::allocator<void> > MyActionFeedback;

typedef boost::shared_ptr< ::upros_message::MyActionFeedback > MyActionFeedbackPtr;
typedef boost::shared_ptr< ::upros_message::MyActionFeedback const> MyActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::MyActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::MyActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::MyActionFeedback_<ContainerAllocator1> & lhs, const ::upros_message::MyActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::MyActionFeedback_<ContainerAllocator1> & lhs, const ::upros_message::MyActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70805092fd20e110765c7b79e8efb737";
  }

  static const char* value(const ::upros_message::MyActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70805092fd20e110ULL;
  static const uint64_t static_value2 = 0x765c7b79e8efb737ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/MyActionFeedback";
  }

  static const char* value(const ::upros_message::MyActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::MyActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Define a feedback message\n"
"float32 progress\n"
"\n"
;
  }

  static const char* value(const ::upros_message::MyActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::MyActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::MyActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::MyActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MYACTIONFEEDBACK_H
