// Generated by gencpp from file upros_message/MyMessage.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MYMESSAGE_H
#define UPROS_MESSAGE_MESSAGE_MYMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct MyMessage_
{
  typedef MyMessage_<ContainerAllocator> Type;

  MyMessage_()
    : key(0)
    , value()  {
    }
  MyMessage_(const ContainerAllocator& _alloc)
    : key(0)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::upros_message::MyMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::MyMessage_<ContainerAllocator> const> ConstPtr;

}; // struct MyMessage_

typedef ::upros_message::MyMessage_<std::allocator<void> > MyMessage;

typedef boost::shared_ptr< ::upros_message::MyMessage > MyMessagePtr;
typedef boost::shared_ptr< ::upros_message::MyMessage const> MyMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::MyMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::MyMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::MyMessage_<ContainerAllocator1> & lhs, const ::upros_message::MyMessage_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::MyMessage_<ContainerAllocator1> & lhs, const ::upros_message::MyMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fafd3516ef178111e41c3e68d4160070";
  }

  static const char* value(const ::upros_message::MyMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfafd3516ef178111ULL;
  static const uint64_t static_value2 = 0xe41c3e68d4160070ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/MyMessage";
  }

  static const char* value(const ::upros_message::MyMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::MyMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 key    # an integer field\n"
"string value   # a string field\n"
;
  }

  static const char* value(const ::upros_message::MyMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::MyMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::MyMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::MyMessage_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<int32_t>::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MYMESSAGE_H
