// Generated by gencpp from file upros_message/MyServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MYSERVICEMSGREQUEST_H
#define UPROS_MESSAGE_MESSAGE_MYSERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct MyServiceMsgRequest_
{
  typedef MyServiceMsgRequest_<ContainerAllocator> Type;

  MyServiceMsgRequest_()
    : input(0)  {
    }
  MyServiceMsgRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int32_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MyServiceMsgRequest_

typedef ::upros_message::MyServiceMsgRequest_<std::allocator<void> > MyServiceMsgRequest;

typedef boost::shared_ptr< ::upros_message::MyServiceMsgRequest > MyServiceMsgRequestPtr;
typedef boost::shared_ptr< ::upros_message::MyServiceMsgRequest const> MyServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::MyServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::upros_message::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::upros_message::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "350f8291236c5b6fb3b8cfcb1672a02e";
  }

  static const char* value(const ::upros_message::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x350f8291236c5b6fULL;
  static const uint64_t static_value2 = 0xb3b8cfcb1672a02eULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/MyServiceMsgRequest";
  }

  static const char* value(const ::upros_message::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 input\n"
;
  }

  static const char* value(const ::upros_message::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::MyServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::MyServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MYSERVICEMSGREQUEST_H
