// Generated by gencpp from file upros_message/MyServiceMsg.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MYSERVICEMSG_H
#define UPROS_MESSAGE_MESSAGE_MYSERVICEMSG_H

#include <ros/service_traits.h>


#include <upros_message/MyServiceMsgRequest.h>
#include <upros_message/MyServiceMsgResponse.h>


namespace upros_message
{

struct MyServiceMsg
{

typedef MyServiceMsgRequest Request;
typedef MyServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MyServiceMsg
} // namespace upros_message


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upros_message::MyServiceMsg > {
  static const char* value()
  {
    return "21d8f69e8f1621953b39ae17e934f4f0";
  }

  static const char* value(const ::upros_message::MyServiceMsg&) { return value(); }
};

template<>
struct DataType< ::upros_message::MyServiceMsg > {
  static const char* value()
  {
    return "upros_message/MyServiceMsg";
  }

  static const char* value(const ::upros_message::MyServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::upros_message::MyServiceMsgRequest> should match
// service_traits::MD5Sum< ::upros_message::MyServiceMsg >
template<>
struct MD5Sum< ::upros_message::MyServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upros_message::MyServiceMsg >::value();
  }
  static const char* value(const ::upros_message::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upros_message::MyServiceMsgRequest> should match
// service_traits::DataType< ::upros_message::MyServiceMsg >
template<>
struct DataType< ::upros_message::MyServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::upros_message::MyServiceMsg >::value();
  }
  static const char* value(const ::upros_message::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upros_message::MyServiceMsgResponse> should match
// service_traits::MD5Sum< ::upros_message::MyServiceMsg >
template<>
struct MD5Sum< ::upros_message::MyServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upros_message::MyServiceMsg >::value();
  }
  static const char* value(const ::upros_message::MyServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upros_message::MyServiceMsgResponse> should match
// service_traits::DataType< ::upros_message::MyServiceMsg >
template<>
struct DataType< ::upros_message::MyServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::upros_message::MyServiceMsg >::value();
  }
  static const char* value(const ::upros_message::MyServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MYSERVICEMSG_H
