// Generated by gencpp from file upros_message/MyServiceMsgResponse.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_MYSERVICEMSGRESPONSE_H
#define UPROS_MESSAGE_MESSAGE_MYSERVICEMSGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct MyServiceMsgResponse_
{
  typedef MyServiceMsgResponse_<ContainerAllocator> Type;

  MyServiceMsgResponse_()
    : output(0)  {
    }
  MyServiceMsgResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int32_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MyServiceMsgResponse_

typedef ::upros_message::MyServiceMsgResponse_<std::allocator<void> > MyServiceMsgResponse;

typedef boost::shared_ptr< ::upros_message::MyServiceMsgResponse > MyServiceMsgResponsePtr;
typedef boost::shared_ptr< ::upros_message::MyServiceMsgResponse const> MyServiceMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::MyServiceMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::MyServiceMsgResponse_<ContainerAllocator1> & lhs, const ::upros_message::MyServiceMsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::MyServiceMsgResponse_<ContainerAllocator1> & lhs, const ::upros_message::MyServiceMsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5fc6b37f5643970fe87c91f31f11e4a";
  }

  static const char* value(const ::upros_message::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5fc6b37f5643970ULL;
  static const uint64_t static_value2 = 0xfe87c91f31f11e4aULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/MyServiceMsgResponse";
  }

  static const char* value(const ::upros_message::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 output\n"
"\n"
;
  }

  static const char* value(const ::upros_message::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyServiceMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::MyServiceMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::MyServiceMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_MYSERVICEMSGRESPONSE_H
