// Generated by gencpp from file upros_message/SingleServo.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_SINGLESERVO_H
#define UPROS_MESSAGE_MESSAGE_SINGLESERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct SingleServo_
{
  typedef SingleServo_<ContainerAllocator> Type;

  SingleServo_()
    : ID(0)
    , Target_position_Angle(0)
    , Rotation_Speed(0)  {
    }
  SingleServo_(const ContainerAllocator& _alloc)
    : ID(0)
    , Target_position_Angle(0)
    , Rotation_Speed(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef int16_t _Target_position_Angle_type;
  _Target_position_Angle_type Target_position_Angle;

   typedef uint16_t _Rotation_Speed_type;
  _Rotation_Speed_type Rotation_Speed;





  typedef boost::shared_ptr< ::upros_message::SingleServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::SingleServo_<ContainerAllocator> const> ConstPtr;

}; // struct SingleServo_

typedef ::upros_message::SingleServo_<std::allocator<void> > SingleServo;

typedef boost::shared_ptr< ::upros_message::SingleServo > SingleServoPtr;
typedef boost::shared_ptr< ::upros_message::SingleServo const> SingleServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::SingleServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::SingleServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::SingleServo_<ContainerAllocator1> & lhs, const ::upros_message::SingleServo_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.Target_position_Angle == rhs.Target_position_Angle &&
    lhs.Rotation_Speed == rhs.Rotation_Speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::SingleServo_<ContainerAllocator1> & lhs, const ::upros_message::SingleServo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::SingleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::SingleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::SingleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::SingleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::SingleServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::SingleServo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::SingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ef01d0888da8fe2f6daabf595b55418";
  }

  static const char* value(const ::upros_message::SingleServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ef01d0888da8fe2ULL;
  static const uint64_t static_value2 = 0xf6daabf595b55418ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::SingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/SingleServo";
  }

  static const char* value(const ::upros_message::SingleServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::SingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n"
"int16 Target_position_Angle\n"
"uint16 Rotation_Speed\n"
;
  }

  static const char* value(const ::upros_message::SingleServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::SingleServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.Target_position_Angle);
      stream.next(m.Rotation_Speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SingleServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::SingleServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::SingleServo_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "Target_position_Angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Target_position_Angle);
    s << indent << "Rotation_Speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Rotation_Speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_SINGLESERVO_H
