// Auto-generated. Do not edit!

// (in-package upros_message.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class CoreMoveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.runing = null;
      this.current_position = null;
    }
    else {
      if (initObj.hasOwnProperty('runing')) {
        this.runing = initObj.runing
      }
      else {
        this.runing = 0;
      }
      if (initObj.hasOwnProperty('current_position')) {
        this.current_position = initObj.current_position
      }
      else {
        this.current_position = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CoreMoveFeedback
    // Serialize message field [runing]
    bufferOffset = _serializer.int8(obj.runing, buffer, bufferOffset);
    // Serialize message field [current_position]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.current_position, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CoreMoveFeedback
    let len;
    let data = new CoreMoveFeedback(null);
    // Deserialize message field [runing]
    data.runing = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [current_position]
    data.current_position = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.current_position);
    return length + 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'upros_message/CoreMoveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '16ad7b9381f50b83dafc17a9791c2ffb';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int8 runing
    geometry_msgs/PoseStamped current_position
    
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CoreMoveFeedback(null);
    if (msg.runing !== undefined) {
      resolved.runing = msg.runing;
    }
    else {
      resolved.runing = 0
    }

    if (msg.current_position !== undefined) {
      resolved.current_position = geometry_msgs.msg.PoseStamped.Resolve(msg.current_position)
    }
    else {
      resolved.current_position = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = CoreMoveFeedback;
