; Auto-generated. Do not edit!


(cl:in-package upros_message-msg)


;//! \htmlinclude CoreMoveGoal.msg.html

(cl:defclass <CoreMoveGoal> (roslisp-msg-protocol:ros-message)
  ((cmd
    :reader cmd
    :initarg :cmd
    :type cl:fixnum
    :initform 0)
   (target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass CoreMoveGoal (<CoreMoveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CoreMoveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CoreMoveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upros_message-msg:<CoreMoveGoal> is deprecated: use upros_message-msg:CoreMoveGoal instead.")))

(cl:ensure-generic-function 'cmd-val :lambda-list '(m))
(cl:defmethod cmd-val ((m <CoreMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upros_message-msg:cmd-val is deprecated.  Use upros_message-msg:cmd instead.")
  (cmd m))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <CoreMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upros_message-msg:target_pose-val is deprecated.  Use upros_message-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<CoreMoveGoal>)))
    "Constants for message type '<CoreMoveGoal>"
  '((:TURN_AROUND . 0)
    (:GO_STRIGHT . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'CoreMoveGoal)))
    "Constants for message type 'CoreMoveGoal"
  '((:TURN_AROUND . 0)
    (:GO_STRIGHT . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CoreMoveGoal>) ostream)
  "Serializes a message object of type '<CoreMoveGoal>"
  (cl:let* ((signed (cl:slot-value msg 'cmd)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CoreMoveGoal>) istream)
  "Deserializes a message object of type '<CoreMoveGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cmd) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CoreMoveGoal>)))
  "Returns string type for a message object of type '<CoreMoveGoal>"
  "upros_message/CoreMoveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CoreMoveGoal)))
  "Returns string type for a message object of type 'CoreMoveGoal"
  "upros_message/CoreMoveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CoreMoveGoal>)))
  "Returns md5sum for a message object of type '<CoreMoveGoal>"
  "c1e16158e8d38eb2844c9923667d0a0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CoreMoveGoal)))
  "Returns md5sum for a message object of type 'CoreMoveGoal"
  "c1e16158e8d38eb2844c9923667d0a0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CoreMoveGoal>)))
  "Returns full string definition for message of type '<CoreMoveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 TURN_AROUND=0~%int8 GO_STRIGHT=1~%int8 cmd~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CoreMoveGoal)))
  "Returns full string definition for message of type 'CoreMoveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 TURN_AROUND=0~%int8 GO_STRIGHT=1~%int8 cmd~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CoreMoveGoal>))
  (cl:+ 0
     1
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CoreMoveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CoreMoveGoal
    (cl:cons ':cmd (cmd msg))
    (cl:cons ':target_pose (target_pose msg))
))
