; Auto-generated. Do not edit!


(cl:in-package upros_message-msg)


;//! \htmlinclude CoreMoveFeedback.msg.html

(cl:defclass <CoreMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((runing
    :reader runing
    :initarg :runing
    :type cl:fixnum
    :initform 0)
   (current_position
    :reader current_position
    :initarg :current_position
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass CoreMoveFeedback (<CoreMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CoreMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CoreMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upros_message-msg:<CoreMoveFeedback> is deprecated: use upros_message-msg:CoreMoveFeedback instead.")))

(cl:ensure-generic-function 'runing-val :lambda-list '(m))
(cl:defmethod runing-val ((m <CoreMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upros_message-msg:runing-val is deprecated.  Use upros_message-msg:runing instead.")
  (runing m))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <CoreMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upros_message-msg:current_position-val is deprecated.  Use upros_message-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CoreMoveFeedback>) ostream)
  "Serializes a message object of type '<CoreMoveFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'runing)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_position) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CoreMoveFeedback>) istream)
  "Deserializes a message object of type '<CoreMoveFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'runing) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_position) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CoreMoveFeedback>)))
  "Returns string type for a message object of type '<CoreMoveFeedback>"
  "upros_message/CoreMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CoreMoveFeedback)))
  "Returns string type for a message object of type 'CoreMoveFeedback"
  "upros_message/CoreMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CoreMoveFeedback>)))
  "Returns md5sum for a message object of type '<CoreMoveFeedback>"
  "16ad7b9381f50b83dafc17a9791c2ffb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CoreMoveFeedback)))
  "Returns md5sum for a message object of type 'CoreMoveFeedback"
  "16ad7b9381f50b83dafc17a9791c2ffb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CoreMoveFeedback>)))
  "Returns full string definition for message of type '<CoreMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 runing~%geometry_msgs/PoseStamped current_position~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CoreMoveFeedback)))
  "Returns full string definition for message of type 'CoreMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 runing~%geometry_msgs/PoseStamped current_position~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CoreMoveFeedback>))
  (cl:+ 0
     1
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_position))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CoreMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CoreMoveFeedback
    (cl:cons ':runing (runing msg))
    (cl:cons ':current_position (current_position msg))
))
