# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from upros_message/MultipleServo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import upros_message.msg

class MultipleServo(genpy.Message):
  _md5sum = "b0bba86e4a57a4c36bff2c5c90926b54"
  _type = "upros_message/MultipleServo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """SingleServo[] servo_gather
================================================================================
MSG: upros_message/SingleServo
uint8 ID
int16 Target_position_Angle
uint16 Rotation_Speed
"""
  __slots__ = ['servo_gather']
  _slot_types = ['upros_message/SingleServo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo_gather

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultipleServo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servo_gather is None:
        self.servo_gather = []
    else:
      self.servo_gather = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.servo_gather)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo_gather:
        _x = val1
        buff.write(_get_struct_BhH().pack(_x.ID, _x.Target_position_Angle, _x.Rotation_Speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servo_gather is None:
        self.servo_gather = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo_gather = []
      for i in range(0, length):
        val1 = upros_message.msg.SingleServo()
        _x = val1
        start = end
        end += 5
        (_x.ID, _x.Target_position_Angle, _x.Rotation_Speed,) = _get_struct_BhH().unpack(str[start:end])
        self.servo_gather.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.servo_gather)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo_gather:
        _x = val1
        buff.write(_get_struct_BhH().pack(_x.ID, _x.Target_position_Angle, _x.Rotation_Speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servo_gather is None:
        self.servo_gather = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo_gather = []
      for i in range(0, length):
        val1 = upros_message.msg.SingleServo()
        _x = val1
        start = end
        end += 5
        (_x.ID, _x.Target_position_Angle, _x.Rotation_Speed,) = _get_struct_BhH().unpack(str[start:end])
        self.servo_gather.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BhH = None
def _get_struct_BhH():
    global _struct_BhH
    if _struct_BhH is None:
        _struct_BhH = struct.Struct("<BhH")
    return _struct_BhH
