# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from upros_message/SingleServo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SingleServo(genpy.Message):
  _md5sum = "5ef01d0888da8fe2f6daabf595b55418"
  _type = "upros_message/SingleServo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 ID
int16 Target_position_Angle
uint16 Rotation_Speed
"""
  __slots__ = ['ID','Target_position_Angle','Rotation_Speed']
  _slot_types = ['uint8','int16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,Target_position_Angle,Rotation_Speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SingleServo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.Target_position_Angle is None:
        self.Target_position_Angle = 0
      if self.Rotation_Speed is None:
        self.Rotation_Speed = 0
    else:
      self.ID = 0
      self.Target_position_Angle = 0
      self.Rotation_Speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BhH().pack(_x.ID, _x.Target_position_Angle, _x.Rotation_Speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.ID, _x.Target_position_Angle, _x.Rotation_Speed,) = _get_struct_BhH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BhH().pack(_x.ID, _x.Target_position_Angle, _x.Rotation_Speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.ID, _x.Target_position_Angle, _x.Rotation_Speed,) = _get_struct_BhH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BhH = None
def _get_struct_BhH():
    global _struct_BhH
    if _struct_BhH is None:
        _struct_BhH = struct.Struct("<BhH")
    return _struct_BhH
