(cl:defpackage upros_message-srv
  (:use )
  (:export
   "ARMPOSITION"
   "<ARMPOSITION-REQUEST>"
   "ARMPOSITION-REQUEST"
   "<ARMPOSITION-RESPONSE>"
   "ARMPOSITION-RESPONSE"
   "MYSERVICEMSG"
   "<MYSERVICEMSG-REQUEST>"
   "MYSERVICEMSG-REQUEST"
   "<MYSERVICEMSG-RESPONSE>"
   "MYSERVICEMSG-RESPONSE"
  ))

